In [1]:
# .unique() method

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [4]:
uniques = obj.unique()
uniques

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [5]:
# .value_counts() method

In [6]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [7]:
# .isin() method

In [8]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [9]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [10]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: str

In [11]:
# Index.get_indexer() method

In [12]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: str

In [13]:
#unique_vals = pd.Series(['c', 'b', 'a'])
unique_vals = to_match.unique()
unique_vals

<StringArray>
['c', 'a', 'b']
Length: 3, dtype: str

In [14]:
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 1, 2, 2, 0, 1])

In [15]:
# .factorize() method

In [16]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: str

In [17]:
pd.factorize(to_match)

(array([0, 1, 2, 2, 0, 1]), Index(['c', 'a', 'b'], dtype='str'))

In [18]:
# for DataFrame

In [19]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [20]:
data['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [21]:
result = data.apply(pd.Series.value_counts).fillna(0)
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [22]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], 
                     "b": [0, 0, 1, 0, 0]})
data

   a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [23]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64