In [1]:
# .reindex() method

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
# method='ffill'

# kind of interpolation
# (forward-fill)

In [6]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: str

In [7]:
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [8]:
# for DataFrame

In [9]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [10]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [11]:
states = ['Texas', 'Utah', 'California']

frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [12]:
frame.reindex(states, axis='columns')

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [13]:
# reindexing using loc operator

In [14]:
frame.loc[['a', 'd', 'c'], ['California', 'Texas']]

   California  Texas
a           2      1
d           8      7
c           5      4